version: "1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
