import type { Metadata } from "next";
import '@/styles/global.scss';

export const metadata: Metadata = {
  title: "Adrián López - npm run van",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: any) {
  return children;
}
